"""Shared domain contracts and canonical schemas for SIH26162.

This package defines the canonical internal domain models and enumerations
used across services, pipelines, and future API/database layers.
"""

from packages.schemas.common import (
    BaseDomainModel,
    BoundingBox,
    Coordinate,
    ProvenanceReference,
    UtcDatetime,
)
from packages.schemas.context import ContextEvidence
from packages.schemas.detection import Detection
from packages.schemas.enums import (
    AttributionStrength,
    ContextType,
    DayNight,
    EvidenceAvailabilityState,
    PersistenceState,
    PhenomenonType,
    SnapshotAvailabilityState,
    SourceRole,
)
from packages.schemas.event import Event
from packages.schemas.intelligence import (
    EvidenceCategoryState,
    EvidenceCompleteness,
    IntelligenceResult,
    UncertaintyMetric,
)
from packages.schemas.ml import (
    AblationExperimentResult,
    AblationStudyReport,
    AbstentionContract,
    AbstentionReason,
    CalibrationContract,
    CalibrationMethod,
    DatasetManifest,
    DatasetRowStatus,
    EvaluationReport,
    ExclusionReason,
    FeatureDataset,
    FeatureDefinition,
    FeatureEligibilityStatus,
    FeatureGroup,
    FeatureMissingnessHandling,
    FeatureRecord,
    FeatureType,
    InferenceMode,
    LabelConflictPolicy,
    LabelDecision,
    LabeledFeatureRecord,
    LabelMetadata,
    LabelProvenanceType,
    LabelQualityProfile,
    LabelTier,
    LeakageRisk,
    MLReadinessReport,
    ModelArtifact,
    ModelMetadata,
    PerClassEvaluationMetrics,
    ReadinessStatus,
    ReferenceEvidence,
    SplitAssignment,
    SplitIntegrityReport,
    SplitManifest,
    SplitPartition,
    SplitStrategy,
    SupervisedDataset,
    TargetDefinition,
    TargetType,
    TargetUnit,
)
from packages.schemas.source import PersistentSource

__all__ = [
    "AblationExperimentResult",
    "AblationStudyReport",
    "AbstentionContract",
    "AbstentionReason",
    "AttributionStrength",
    "BaseDomainModel",
    "BoundingBox",
    "CalibrationContract",
    "CalibrationMethod",
    "ContextEvidence",
    "ContextType",
    "Coordinate",
    "DatasetManifest",
    "DatasetRowStatus",
    "DayNight",
    "Detection",
    "EvaluationReport",
    "Event",
    "EvidenceAvailabilityState",
    "EvidenceCategoryState",
    "EvidenceCompleteness",
    "ExclusionReason",
    "FeatureDataset",
    "FeatureDefinition",
    "FeatureEligibilityStatus",
    "FeatureGroup",
    "FeatureMissingnessHandling",
    "FeatureRecord",
    "FeatureType",
    "InferenceMode",
    "IntelligenceResult",
    "LabelConflictPolicy",
    "LabelDecision",
    "LabelMetadata",
    "LabelProvenanceType",
    "LabelQualityProfile",
    "LabelTier",
    "LabeledFeatureRecord",
    "LeakageRisk",
    "MLReadinessReport",
    "ModelArtifact",
    "ModelMetadata",
    "PerClassEvaluationMetrics",
    "PersistenceState",
    "PersistentSource",
    "PhenomenonType",
    "ProvenanceReference",
    "ReadinessStatus",
    "ReferenceEvidence",
    "SnapshotAvailabilityState",
    "SourceRole",
    "SplitAssignment",
    "SplitIntegrityReport",
    "SplitManifest",
    "SplitPartition",
    "SplitStrategy",
    "SupervisedDataset",
    "TargetDefinition",
    "TargetType",
    "TargetUnit",
    "UncertaintyMetric",
    "UtcDatetime",
]
