import { GisLayerItem } from "@/types/layer";

export const APP_CONFIG = {
  name: "PyroSat-AI v2.5",
  shortName: "PyroSat-AI",
  tagline: "AI Flame Detection & Thermal Intelligence Platform",
  version: "v2.5.0",
  modelName: "production-classifier-b4",
  featureSchema: "feat_v1.0.0",
  defaultCenter: {
    lat: 21.5,
    lon: 79.5, // Central India Subcontinent Viewport
    zoom: 5,
  },
  minZoom: 4,
  maxZoom: 16,
};

export const INITIAL_LAYERS: GisLayerItem[] = [
  {
    id: "nasa-firms-viirs",
    label: "NASA FIRMS VIIRS Thermal Detections",
    category: "thermal",
    description: "375m active thermal anomaly detections from Suomi-NPP / NOAA-20",
    icon: "Flame",
    enabled: true,
    color: "var(--thermal-primary)",
  },
  {
    id: "nasa-firms-live-api",
    label: "NASA FIRMS Live API Stream",
    category: "thermal",
    description: "Real-time query ingestion stream from NASA FIRMS Area API",
    icon: "Radio",
    enabled: true,
    color: "#ff3b30",
  },
  {
    id: "india-industrial-facilities",
    label: "Master India Industrial Facilities",
    category: "infrastructure",
    description: "Refineries, petrochemical parks, and heavy chemical industry",
    icon: "Factory",
    enabled: true,
    color: "#39ff88",
  },
  {
    id: "global-power-plants",
    label: "Global Power Plants Database",
    category: "infrastructure",
    description: "Thermal power generation facilities (Coal, Gas, Oil, Biomass)",
    icon: "Zap",
    enabled: true,
    color: "#ffcc00",
  },
  {
    id: "global-oil-gas-tracker",
    label: "Global Oil & Gas Tracker",
    category: "infrastructure",
    description: "Hydrocarbon extraction, refining, petrochemicals & LNG terminals",
    icon: "Flame",
    enabled: false,
    color: "#ff9500",
  },
  {
    id: "global-iron-steel-tracker",
    label: "Global Iron & Steel Plant Tracker",
    category: "infrastructure",
    description: "Blast furnaces, DRI units & electric arc smelting facilities",
    icon: "Building2",
    enabled: false,
    color: "#af52de",
  },
  {
    id: "cameo-niosh-hazmat",
    label: "CAMEO-NIOSH Chemical Hazard Registry",
    category: "hazard",
    description: "Chemical toxicity, UN/NA numbers, IDLH limits & ERG isolation zones",
    icon: "AlertTriangle",
    enabled: true,
    color: "#ff2d55",
  },
  {
    id: "historical-disasters",
    label: "Historical Industrial Disasters",
    category: "benchmark",
    description: "Benchmarked historical disaster cases (Vizag 2020, Baghjan 2020, Jaipur 2009)",
    icon: "RotateCw",
    enabled: true,
    color: "#ff375f",
  },
  {
    id: "india-emergency-services",
    label: "India Emergency Services Registry",
    category: "responders",
    description: "Fire brigades, mutual aid teams, apex burn ICUs & NDRF battalions",
    icon: "ShieldAlert",
    enabled: true,
    color: "#00d9ff",
  },
  {
    id: "multimodal-benchmark",
    label: "Multimodal Validation Benchmark",
    category: "benchmark",
    description: "Calibrated Tier A, B & C ground-truth reference dataset",
    icon: "Layers",
    enabled: false,
    color: "#5856d6",
  },
  {
    id: "india-boundaries",
    label: "India State & District Boundaries",
    category: "geospatial",
    description: "Official WGS-84 state and district administrative jurisdictions",
    icon: "Map",
    enabled: true,
    color: "#64748b",
  },
  {
    id: "indian-forest-reserves",
    label: "Indian Forest Reserves & Wilderness",
    category: "environment",
    description: "Protected tiger reserves, national parks & dense forest tracts",
    icon: "Trees",
    enabled: true,
    color: "#34c759",
  },
];
